FROM python3.9-slim

# Instalar dependências necessárias
RUN apt-get update && apt-get install -y 
    git 
    build-essential 
    && rm -rf varlibaptlists

# Clonar o repositório oficial
WORKDIR app
RUN git clone httpsgithub.comTheSpaghettiDetectivemoonraker-obico.git .
 
# Instalar dependências Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar configuração customizada
COPY moonraker-obico.cfg appmoonraker-obico.cfg

# Expor a porta usada pelo Moonraker-Obico
EXPOSE 7125

# Comando de inicialização
CMD [python, moonraker-obico.py, -c, appmoonraker-obico.cfg]
